/* eslint-disable import/prefer-default-export */

export const SET_TABLE_DATA_SETTINGS_SIP = 'SET_TABLE_DATA_SETTINGS_SIP';

export const SET_ARR_NUMBERS_SETTINGS_SIP = 'SET_ARR_NUMBERS_SETTINGS_SIP';

export const SET_NUMBER_VALUE_SETTINGS_SIP = 'SET_NUMBER_VALUE_SETTINGS_SIP';