/* eslint-disable import/prefer-default-export */

export const SET_TAB_VALUE_SETTINGS = 'SET_TAB_VALUE_SETTINGS';

export const SET_ERROR_MESSAGE_SNACK_BAR_SETTINGS = 'SET_ERROR_MESSAGE_SNACK_BAR_SETTINGS';
export const SET_MESSAGE_SNACK_BAR_SETTINGS = 'SET_MESSAGE_SNACK_BAR_SETTINGS';
export const SET_OPEN_MESSAGE_SNACK_BAR_SETTINGS = 'SET_OPEN_MESSAGE_SNACK_BAR_SETTINGS';

export const REQUEST_POSTS_SETTINGS = 'REQUEST_POSTS_SETTINGS';
export const RECEIVE_POSTS_SETTINGS = 'RECEIVE_POSTS_SETTINGS';
export const SET_USER_ACCOUNT_SETTINGS = 'SET_USER_ACCOUNT_SETTINGS';

export const SET_MESSAGE_CIRCLE_PROGRESS_SETTINGS = 'SET_MESSAGE_CIRCLE_PROGRESS_SETTINGS';
export const SET_OPEN_CIRCLE_PROGRESS_SETTINGS = 'SET_OPEN_CIRCLE_PROGRESS_SETTINGS';
export const SET_OPEN_DIALOG_TEXT_SETTINGS = 'SET_OPEN_DIALOG_TEXT_SETTINGS';
export const SET_TITLE_DIALOG_TEXT_SETTINGS = 'SET_TITLE_DIALOG_TEXT_SETTINGS';
export const SET_CONTENT_DIALOG_TEXT_SETTINGS = 'SET_CONTENT_DIALOG_TEXT_SETTINGS';

export const SET_ON_CLICK_CANCEL_DIALOG_DEL_SETTINGS = 'SET_ON_CLICK_CANCEL_DIALOG_DEL_SETTINGS';

export const SET_ON_CLICK_OK_DIALOG_DEL_SETTINGS = 'SET_ON_CLICK_OK_DIALOG_DEL_SETTINGS';

export const SET_OPEN_DIALOG_DEL_SETTINGS = 'SET_OPEN_DIALOG_DEL_SETTINGS';

export const SET_TITLE_DIALOG_DEL_SETTINGS = 'SET_TITLE_DIALOG_DEL_SETTINGS';
